### ISSUE TITLE
No licenses clearly specified

### ISSUE THREAD

**Issue by sampablokuper** [abilian/abilian-sbe#22]
Please could the code in this repository be clearly licensed under a [GPL-Compatible Free Software license](https://www.gnu.org/licenses/license-list.html), and a copy of the license included in the repository? I would suggest the [AGPLv3](https://www.gnu.org/licenses/license-list.html#AGPLv3.0) license.

Please could a [documentation license](https://www.gnu.org/licenses/license-list.html#OtherLicenses) also be specified?

Thanks!

**Comment by sfermigier** [comment]
The licence is specified in the setup.py file:

  license='LGPL',

And at this point there is no documentation, but when there will be, we will use the GFDL.

**Comment by sampablokuper** [comment]
> And at this point there is no documentation, but when there will be, we will use the GFDL.

Ah, thanks, and sorry for the confusion. I had [these docs](http://docs.abilian.com/en/latest/) in mind when I reported this bug. It would be great if you could use GFDL for those!

>The licence is specified in the setup.py file: `license='LGPL',`

It's great that you're using a free software license. However, if the only mention of the license is on line 44 of a code file, in the middle of a function call, then it is reasonable for me to think that the code in the repository is _not_ clearly licensed :) Your current licensing approach will also not show up with the GitHub [API](https://developer.github.com/v3/licenses/) or any other API that uses a similar lookup strategy to it.

**Comment by sfermigier** [comment]
> However, if the only mention of the license is on line 44 of a code file, in the middle of a function call,

It's not *any* code file, it's `setup.py`, the standard way to specify metadata about a software package in Python, and it's the source of information used by all the packaging tools in the Python ecosystem (including <http://pypi.python.org/>).

Anyway, thanks for your feedback, I'll make a few adjustments, including adding a `LICENSE.txt` at the root.
